[project]
name = "ayeye"
version = "0.1.0"
description = "Consistent LLM wrapper for a variety of online AI model providers"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.49.0",
    "google-genai>=1.3.0",
    "openai>=1.65.2",
]
